### PR TITLE
Support terraform 0.12

### PR DESCRIPTION
**Pull request by aedades**
See related issue: https://github.com/jianyuan/terraform-provider-sentry/issues/36.

Followed the [guide on upgrading to the latest terraform SDK](https://www.terraform.io/docs/extend/terraform-0.12-compatibility.html#upgrading-to-the-latest-terraform-sdk) and ran:
```
go get github.com/hashicorp/terraform@v0.12.0
go mod tidy
go mod vendor
```

Tests passed locally:
```bash
❯ make test
?       github.com/jianyuan/terraform-provider-sentry   [no test files]
=== RUN   TestAccSentryKeyDataSource_basic
--- PASS: TestAccSentryKeyDataSource_basic (3.26s)
=== RUN   TestAccSentryKeyDataSource_first
--- PASS: TestAccSentryKeyDataSource_first (2.96s)
=== RUN   TestAccSentryKeyDataSource_name
--- PASS: TestAccSentryKeyDataSource_name (3.81s)
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProviderImpl
--- PASS: TestProviderImpl (0.00s)
=== RUN   TestAccSentryKey_basic
--- PASS: TestAccSentryKey_basic (4.30s)
=== RUN   TestAccSentryProject_basic
--- PASS: TestAccSentryProject_basic (4.06s)
=== RUN   TestAccSentryTeam_basic
--- PASS: TestAccSentryTeam_basic (1.98s)
PASS
ok      github.com/jianyuan/terraform-provider-sentry/sentry    21.488s
```

Also added some info in the readme for building and testing the provider.

### CODE REVIEW

**Comment by bee-keeper** [comment]
Have just upgraded to 0.12 and rebuilt this provider locally.  Can confirm works fine.

**Comment by jonbesga** [comment]
Can this PR be merged already?

**Comment by jianyuan** [comment]
Looks good @aedades. Thank you!

**Comment by bjaworski3** [comment]
@jianyuan Will there be a release soon including the terraform 0.12 changes?

**Pull request merged**
