### PR TITLE
Issue Grouping support

### PR DESCRIPTION
**Pull request by mtanda**
will fix https://github.com/jianyuan/terraform-provider-sentry/issues/230

### CODE REVIEW

**Comment by ThePletch** [comment]
@jianyuan this is an important feature for my team, can this be prioritized?

**Comment by alxckn** [comment]
We are looking forward to this as well

**Comment by jozefizso** [comment]
It would be great to make this happen.

This would make it much easier to manage complex Issue Grouping rules.

**Comment by boh-dan** [comment]
@jianyuan it is important for us too!

**Comment by ledniov** [comment]
Hi @jianyuan , could you please check this PR? This feature would help us to reflect the full Sentry configuration of the project using our Terraform code.

**Comment by jianyuan** [comment]
Reimplemented in https://github.com/jianyuan/terraform-provider-sentry/pull/510

**Pull request closed without merging**
