### PR TITLE
Fix importin rule resources

### PR DESCRIPTION
**Pull request by rabunkosar-dd**
This fixes the issue with rule reads not being written to state.

### CODE REVIEW

**Comment by flevour** [comment]
👍 thanks @rabunkosar-dd !

**Comment by rabunkosar-dd** [comment]
Hey @jianyuan, 
is it possible to review this?

**Comment by wgebis** [comment]
Hello @jianyuan! I'm also interested to merge this PR :), looks it will solve my issues with resource updates. 
Thanks @rabunkosar-dd 👍

**Comment by ivanmartos** [comment]
Hello @jianyuan ! Is there something blocking this PR? Is there something that needs to be done?

**Pull request merged**
