### PR TITLE
Add Sentry APM Resource

### PR DESCRIPTION
**Pull request by javaadsnappcar**
This PR will add the ability to create a Sentry Application Performance Monitoring (APM) alert rule using the terraform configuration.

This PR relies on changing the underlying Go client in this PR: https://github.com/jianyuan/go-sentry/pull/25. Because of that, I changed all the references to point to my version of the Go Client so I could test the resource.

When/If the underlying Go Client is merged then I can reset the references.

Disclaimer: I am new to GoLang so there might be some obvious errors.

The new sentry apm rule can be defined as:
```
resource "sentry_apm_rule" "default" {
  organization      = "${sentry_organization.my_organization.id}"
  project           = "${sentry_project.web_app.id}"
  name              = "test-apm-rule"
  dataset           = "transactions"
  query             = "http.url:http://testservice.com/stats"
  time_window       = 50.0
  aggregate         = "p50(transaction.duration)"
  threshold_type    = 0
  resolve_threshold = 100.0

  triggers {
    actions           = []
    alert_threshold   = 1000
    label             = "critical"
    resolve_threshold = 100.0
    threshold_type    = 0
  }

  triggers {
    actions = []
    alert_threshold   = 500
    label             = "warning"
    resolve_threshold = 100.0
    threshold_type    = 0
  }

  projects = ["${sentry_project.web_app.id}"]
}
```

### CODE REVIEW

**Comment by javaadsnappcar** [comment]
Would it be possible for someone to take a look at this PR, I am happy to implement any changes to get this integrated.

**Comment by jianyuan** [comment]
@javaadsnappcar Apologies for the delay. I will review this.

I've just released [go-sentry v1.3.0](https://github.com/jianyuan/go-sentry/releases/tag/v1.3.0). Could you switch your imports to that and run `go mod tidy`?

**Comment by javaadsnappcar** [comment]
@jianyuan thanks very much for looking at this. No worries about the delay, life happens. 

I removed all the changes that I had specifically for testing my own version of the Go client so all the changes should now be just for the new sentry rule type. I changed the version to `1.3.0` and ran `go mod tidy`

**Comment by jianyuan** [comment]
@javaadsnappcar In hindsight, I think we should call the resource `sentry_alert_rule` instead of `sentry_apm_rule` so that it matches the API path (i.e. `/api/0/projects/the-interstellar-jurisdiction/pump-station/alert-rules/`).

Otherwise, everything looks good to me.

**Comment by javaadsnappcar** [comment]
@jianyuan the go-client will still refer to the CRUD actions as `apm` though, for example `APMRuleService` in the go-client? Is that fine?

**Comment by jianyuan** [comment]
> @jianyuan the go-client will still refer to the CRUD actions as `apm` though, for example `APMRuleService` in the go-client? Is that fine?

Leave that with me. I can rename them in a future release.

**Comment by javaadsnappcar** [comment]
@jianyuan okay no worries, thank you. I've renamed everything now to `alert` and `Alert` where appropriate instead of `apm` and `APM`.

**Comment by javaadsnappcar** [comment]
@jianyuan thanks for merging this. I see that I've messed something up and broken the build. I'll see how to fix this as I did not have those errors when I built the provider locally.

**Pull request merged**
