### PR TITLE
Feature: Organization repository code mapping

### PR DESCRIPTION
**Pull request by danielpoonwj**
## Purpose

Thanks for this project @jianyuan!

I'm using this provider to provision Sentry projects for our services and one crucial feature I was looking to implement was [Stack Trace Linking](https://docs.sentry.io/product/integrations/source-code-mgmt/github/#stack-trace-linking), specifically for Github.

## Approach

This feature requires 3 components:

### 1. Github Organization Integration (**data**: `sentry_organization_integration`) 
[Docs](https://docs.sentry.io/product/integrations/source-code-mgmt/github/#install)

  - I'm not sure if this can be created programmatically, but there's extra actions that need to be done on the Github side to accept the Github Apps installation. Anyway this only needs to be done once, so it can be installed manually for now.
  - The Organization Integration ID needs to be retrievable. Hence implementing a data source.

### 2. Github Organization Repository (**resource**: `sentry_organization_repository_github`)
[Docs](https://docs.sentry.io/product/releases/setup/release-automation/)

  - This is classified as under release and commit tracking, but the Repository is referenced when creating code mappings
  - If only release management is required, implementing this resource would be sufficient

### 3. Organization Code Mapping (**resource**: `sentry_organization_code_mapping`)
[Docs](https://docs.sentry.io/product/integrations/source-code-mgmt/github/#stack-trace-linking)

  - This is the resource that does the Stack Trace Linking. It references ids from the other resources

Note: The verbose names mirror the internal naming of the APIs:
- [`organization_integration`](https://github.com/getsentry/sentry/blob/22.7.0/src/sentry/api/endpoints/integrations/organization_integrations/index.py)
- [`organization_repository`](https://github.com/getsentry/sentry/blob/22.7.0/src/sentry/api/endpoints/organization_repositories.py)
- [`organization_code_mapping`](https://github.com/getsentry/sentry/blob/22.7.0/src/sentry/api/endpoints/organization_code_mappings.py)

## Example

```terraform
# Retrieve the Github organization integration
data "sentry_organization_integration" "github" {
  organization = "my-organization"
  provider_key = "github"
  name         = "my-github-organization"
}

resource "sentry_project" "this" {
  organization = "my-organization"

  team = "my-team"
  name = "Web App"
  slug = "web-app"

  platform    = "javascript"
  resolve_age = 720
}

resource "sentry_organization_repository_github" "this" {
  organization   = "my-organization"
  integration_id = data.sentry_organization_integration.github.internal_id
  identifier     = "my-github-organization/my-github-repo"
}

resource "sentry_organization_code_mapping" "this" {
  organization   = "my-organization"
  integration_id = data.sentry_organization_integration.github.internal_id
  repository_id  = sentry_organization_repository_github.this.internal_id
  project_id     = sentry_project.this.internal_id

  default_branch = "main"
  stack_root     = "/"
  source_root    = "src/"
}
```

## Limitations
- I've only been able to verify this with the Github integration, but other source code management services should be supported, but I don't have the environments available to confirm what parameters are accepted. However, I've deliberately separated the resource `sentry_organization_repository_github` to be Github specific. If there are other SCM services to integrate, it can be a different resource.

- The APIs for [`organization_repository`](https://github.com/getsentry/sentry/blob/22.7.0/src/sentry/api/endpoints/organization_repository_details.py) and [`organization_code_mapping`](https://github.com/getsentry/sentry/blob/22.7.0/src/sentry/api/endpoints/organization_code_mapping_details.py) do **not** have GET `/{id}` endpoints for details. So we have to list and filter in code, not ideal but it's the only workaround. There may be performance issues if there's a significant amount of data.

- I'm not sure how to write acc tests for this as it's reliant on first setting up the Github Organization Integration.

## TODO
- Merge https://github.com/jianyuan/go-sentry/pull/64 and restore reference in go.mod

### CODE REVIEW

**Comment by jianyuan** [comment]
Thanks for your PR, @danielpoonwj!

I have gone ahead and merged https://github.com/jianyuan/go-sentry/pull/64. Please could you update the go modules accordingly? Otherwise, your PR looks really good!

**Comment by danielpoonwj** [comment]
> Thanks for your PR, @danielpoonwj!
> 
> I have gone ahead and merged [jianyuan/go-sentry#64](https://github.com/jianyuan/go-sentry/pull/64). Please could you update the go modules accordingly? Otherwise, your PR looks really good!

Done! Thank you!

**Comment by danielpoonwj** [comment]
Hi @jianyuan! The PR is ready, could you help to review it?

**Comment by danielpoonwj** [comment]
Thanks @jianyuan! Could you publish a new release so we can make use of this feature?

**Pull request merged**
