### PR TITLE
Create SentryOrganizationRepositoryGitlab resource

### PR DESCRIPTION
**Pull request by Sander0542**
This is simply a copy of the GitHub resource, but with the required changes to make it work with GitLab

### CODE REVIEW

**Comment by cuongquach** [comment]
@jianyuan this is quiet useful for us, could you review it ?

**Comment by InsidersByte** [comment]
@jianyuan could you please review this. It would be really useful for me.

**Comment by InsidersByte** [comment]
thank you @jianyuan 👍

**Comment by jianyuan** [comment]
This is addressed in https://github.com/jianyuan/terraform-provider-sentry/pull/500 (New `organization_repository` resource)

**Pull request closed without merging**
