### PR TITLE
feat: Support events type on alerts.

### PR DESCRIPTION
**Pull request by eugeniykurasov**

### CODE REVIEW

**Comment by eugeniykurasov** [comment]
@jianyuan Hi, can you please approve for workflow run?

**Comment by jianyuan** [comment]
I'm not sure why the GitHub secrets are not passed into the workflow. I'll approve and merge it anyways and let the tests run on the main branch.

Thanks for your contributions, @eugeniykurasov!

**Review by jianyuan — APPROVED** [review]

**Comment by eugeniykurasov** [comment]
Thanks for merge.
I will find credentials for local run and prepare fix for test.

**Comment by jianyuan** [comment]
@eugeniykurasov After doing some testing, it seems that the get metric alert endpoint that is nested under the "projects" resource does not return the event types. We will need to switch to the one that is nested under the "organisations" resource:

1. https://sentry.io/api/0/projects/terraform-provider-sentry/project-name/alert-rules/110484/ - does not contain `eventTypes`
2. https://sentry.io/api/0/organizations/terraform-provider-sentry/alert-rules/110484/ - contains `eventTypes`

I will fix this shortly.

**Pull request merged**
